
-- Aqui estamos criando nosso banco de dados (ele é criado apenas se não existir).
-- Nomeamos nosso banco de dados como HABITAE e por fim, selecionamos.
CREATE DATABASE IF NOT EXISTS HABITAE;
USE HABITAE;

-- AQUI ESTAMOS CRIANDO AS ENTIDADES E DEFININDO SEUS ATRIBUTOS
CREATE TABLE EMPRESA (
    CNPJ VARCHAR(15) UNIQUE PRIMARY KEY ,
    ID_FUNCIONARIO INT,
    NOME VARCHAR(30),
    TELEFONE VARCHAR(15),
    ENDERECO_FISICO VARCHAR(30)
);

CREATE TABLE ANUNCIO (
    ID_ANUNCIO INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_IMOVEL INTEGER,
    REDE VARCHAR(20),
    NOME VARCHAR(20),
    VALOR FLOAT(10,2)
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_RESERVA INT,
    ID_USUARIO INT ,
    VALOR FLOAT(10,2),
    NOME VARCHAR(30),
    TIPO VARCHAR(30),
    DATA DATE
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INTEGER PRIMARY KEY UNIQUE AUTO_INCREMENT,
    CPF VARCHAR(14),
    NOME VARCHAR(30),
    TELEFONE VARCHAR(11),
    UNIQUE (ID_FUNCIONARIO, CPF)
);

CREATE TABLE ENDERECO (
    ID_ENDERECO INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    CEP VARCHAR(9),
    RUA VARCHAR(100),
    NUMERO VARCHAR(10),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2)
);

CREATE TABLE IMOVEL (
    ID_IMOVEL INTEGER PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_ENDERECO INT,
    ID_USUARIO INT,
    ID_ANUNCIO INT,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE RESERVA (
    ID_RESERVA INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_IMOVEL INT,
    ID_NOTA INT,
    CHECKIN DATE,
    CHECKOUT DATE
);

CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(15),
    CPF VARCHAR(14)
);

CREATE TABLE NOTA_FISCAL (
    ID_NOTA INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_PAGAMENTO INT,
    VALOR FLOAT(10,2),
    NOME VARCHAR(30),
    TIPO VARCHAR(30),
    DATA DATE
);

-- Chamamos a entidade empresa pra começar a trabalhar com a definição das FK's (chaves estrangeiras)
SELECT * FROM EMPRESA;

-- A partir daqui estamos definindo as chaves estrangeiras do banco de dados.
ALTER TABLE EMPRESA
ADD CONSTRAINT FK_EMPRESA_3
FOREIGN KEY (ID_FUNCIONARIO)
REFERENCES FUNCIONARIO(ID_FUNCIONARIO);
 
ALTER TABLE ANUNCIO ADD CONSTRAINT FK_ANUNCIO_3
    FOREIGN KEY (ID_IMOVEL)
    REFERENCES IMOVEL(ID_IMOVEL);
 
ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_3
    FOREIGN KEY (ID_RESERVA)
    REFERENCES RESERVA(ID_RESERVA);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_USUARIO_3
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO);
    
ALTER TABLE IMOVEL ADD CONSTRAINT FK_IMOVEL_4
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO(ID_ENDERECO);
-- here v

ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_3
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO);
 
 ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_4
    FOREIGN KEY (ID_IMOVEL)
    REFERENCES IMOVEL(ID_IMOVEL);
    
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_5
    FOREIGN KEY (ID_NOTA)
    REFERENCES NOTA_FISCAL(ID_NOTA);
 
ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_NOTA_FISCAL_3
    FOREIGN KEY (ID_PAGAMENTO)
    REFERENCES PAGAMENTO(ID_PAGAMENTO);
