
-- Aqui estamos criando nosso banco de dados (ele é criado apenas se não existir).
-- Nomeamos nosso banco de dados como HABITAE e por fim, selecionamos.
CREATE DATABASE IF NOT EXISTS HABITAE;
USE HABITAE;

-- AQUI ESTAMOS CRIANDO AS ENTIDADES E DEFININDO SEUS ATRIBUTOS
CREATE TABLE EMPRESA (
    CNPJ INT UNIQUE PRIMARY KEY NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    ENDERECO_FISICO VARCHAR(30) NOT NULL
);

CREATE TABLE ANUNCIO (
    ID_ANUNCIO INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
    CNPJ INT NOT NULL,
    REDE ENUM("Online","Impresso",'Tv',"Outdoor") NOT NULL
    DESCRICAO VARCHAR(100),
    VALOR FLOAT(10,2) NOT NULL
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
    ID_RESERVA INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    DATA_VALIDADE DATA NOT NULL,
    DATA_PAGAMENTO DATA NOT NULL,
    TIPO ENUM('PIX', 'Cartão de Débito', 'Cartão de Crédito', 'Boleto', 'Dinheiro') NOT NULL
    );

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
    CNPJ INT NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
);

CREATE TABLE ENDERECO (
    ID_ENDERECO INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    CEP CHAR(9) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    NUMERO INT NOT NULL,
);

CREATE TABLE IMOVEL (
    ID_IMOVEL INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    CNPJ INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    INTENCAO ENUM('Venda', 'Aluguel') NOT NULL,
    TIPO ENUM('Apartamento', 'Casa', 'Comercial') NOT NULL,
    CPF_PROPRIETARIO INT NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE RESERVA (
    ID_RESERVA INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_IMOVEL INT NOT NULL,
    CHECKIN DATE NOT NULL,
    CHECKOUT DATE NOT NULL
);

CREATE TABLE USUARIO (
    ID_USUARIO INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CPF VARCHAR(14) NOT NULL
);

CREATE TABLE NOTA_FISCAL (
    ID_NOTA INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    ID_PAGAMENTO INT NOT NULL,
    DATA_EMISSAO TIMESTAMP NOT NULL
);

-- Chamamos a entidade empresa pra começar a trabalhar com a definição das FK's (chaves estrangeiras)
SELECT * FROM EMPRESA;

-- A partir daqui estamos definindo as chaves estrangeiras do banco de dados.
ALTER TABLE EMPRESA
ADD CONSTRAINT FK_EMPRESA_3
FOREIGN KEY (ID_FUNCIONARIO)
REFERENCES FUNCIONARIO(ID_FUNCIONARIO);
 
ALTER TABLE ANUNCIO ADD CONSTRAINT FK_ANUNCIO_3
    FOREIGN KEY (ID_IMOVEL)
    REFERENCES IMOVEL(ID_IMOVEL);
 
ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_3
    FOREIGN KEY (ID_RESERVA)
    REFERENCES RESERVA(ID_RESERVA);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_USUARIO_3
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO);
    
ALTER TABLE IMOVEL ADD CONSTRAINT FK_IMOVEL_4
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO(ID_ENDERECO);
-- here v

ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_3
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO);
 
 ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_4
    FOREIGN KEY (ID_IMOVEL)
    REFERENCES IMOVEL(ID_IMOVEL);
    
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_5
    FOREIGN KEY (ID_NOTA)
    REFERENCES NOTA_FISCAL(ID_NOTA);
 
ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_NOTA_FISCAL_3
    FOREIGN KEY (ID_PAGAMENTO)
    REFERENCES PAGAMENTO(ID_PAGAMENTO);
